markdown: kramdown
# markdown: redcarpet
# markdown: rdiscount

kramdown:
  entity_output: symbolic

encoding: utf-8

exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

navigation:
 - text: Home
   url: /
   class: home
 - text: About me
   url: /about.html
 - text: Publications
   url: /publications.html
 - text: Research
   url: /research.html

# GitHub set these settings anyway
safe: true
lsi: false
# pygments: true
highlighter: rouge
