markdown: kramdown
# markdown: redcarpet
# markdown: rdiscount

kramdown:
  entity_output: symbolic

encoding: utf-8

exclude:
- README.md
- Gemfile
- Gemfile.lock

navigation:
 - text: Home
   url: /index.html
   class: home
 - text: About me
   url: /about.html
 - text: Publications
   url: /publications.html
 - text: Research
   url: /research.html
 - text: Resources
   url: http://www.ifs.tuwien.ac.at/~rind/w/
   class: external

# GitHub set these settings anyway
safe: true
lsi: false
pygments: true

