markdown: kramdown
# markdown: redcarpet
# markdown: rdiscount
encoding: utf-8

#baseurl: /TimeBench
exclude:
- README.md
- Gemfile
- Gemfile.lock

# GitHub set these settings anyway
safe: true
lsi: false
pygments: true

